### ISSUE TITLE
KaTex 的 lim 公式显示位置有问题

### ISSUE THREAD

**Issue by OscarShen** [JaxsonWang/Editormd#1]
![image](https://user-images.githubusercontent.com/13450440/42919700-c1d5dc6c-8b45-11e8-88cd-6638d0833486.png)
左边是 KaTex 编码，▽x->0 应该在 lim 的下方。

![image](https://user-images.githubusercontent.com/13450440/42919863-9967bf06-8b46-11e8-896b-bb0d54b3e6e9.png)
这是在你提供的 example 里编写的，左右对比，而且 ' 不能直接使用。

![image](https://user-images.githubusercontent.com/13450440/42919886-a95fb332-8b46-11e8-8a3f-f4b93afc1e64.png)
这是 KaTex 官网的显示。

**Comment by JaxsonWang** [comment]
您看下截图就明白了
![image](https://user-images.githubusercontent.com/16836692/42939951-390c603c-8b8a-11e8-959b-45e39cb9f30b.png)

我这样做是区分行内公式和多行公式。
