### ISSUE TITLE
在WordPress中mermaid使用问题

### ISSUE THREAD

**Issue by BrandonXie** [JaxsonWang/Editormd#2]
Dear JaxsonWang：
在使用WP时遇到了个小问题。
下了插件后，编辑器中如下填写，
```mermaid
graph TB;
  A-->B;
```
编辑器预览结果能正常生成图的，在整个页面预览或者发布后却不能生成相关图。

**Comment by JaxsonWang** [comment]
请在插件设置页开启兼容模式

**Comment by BrandonXie** [comment]
Thk，根据提示已解决，准确的说是在插件设置->绘图设置: 启用支持绘图
