### ISSUE TITLE
请问WordPress插件版本，怎么定制（删除）工具栏按钮呢？

### ISSUE THREAD

**Issue by chenzhikang** [JaxsonWang/Editormd#3]
请问WordPress插件版本，怎么定制（删除）工具栏按钮呢？

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/blob/master/assets/Config/editormd.js#L18-L37

fullToolBar = 文章界面
simpleToolBar = 前端评论界面
miniToolBar = 后台评论管理界面

至于数值你对这图标看吧。

**Comment by chenzhikang** [comment]
收到，谢谢！

**Comment by chenzhikang** [comment]
刚才分析了下这个js文件的加载，应该是使用了cdn加速了【ttp://cdn.jsdelivr.net/wp/wp-editormd/branches/20180821/assets/Config/editormd.min.js?ver=6.1.2】
现在我有这种需求：想定制工具栏的按钮。
即使我把 脚本引用改为本地路径，那么wp插件已更新的话，岂不是就覆盖并重新使用cdn了？
这种情况是不是可以留个口子，允许用户将配置信息保留在本地？

**Comment by JaxsonWang** [comment]
你既然说定制了 完全可以弄个分支自己修改用。

正好WP-Editor.md以后不再出现重大更新了，除非有重大BUG。

我现在全力维护WP-HyperMD这个插件。

**Comment by chenzhikang** [comment]
是的。谢谢！
